import 'dart:io';
import 'dart:typed_data';

import 'package:fbr_tax_helper/features/transactions/domain/entities/transaction.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class TransactionReportService {
  const TransactionReportService();

  Future<void> printComparisonReport({
    required List<Transaction> firstTransactions,
    required List<Transaction> secondTransactions,
    required String firstLabel,
    required String secondLabel,
  }) async {
    await Printing.layoutPdf(
      name: 'Filer Flow Comparison Report',
      onLayout: (format) => buildComparisonReport(
        firstTransactions: firstTransactions,
        secondTransactions: secondTransactions,
        firstLabel: firstLabel,
        secondLabel: secondLabel,
        pageFormat: format,
      ),
    );
  }

  Future<Uint8List> buildComparisonReport({
    required List<Transaction> firstTransactions,
    required List<Transaction> secondTransactions,
    required String firstLabel,
    required String secondLabel,
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    final first = _ReportPeriodTotals.from(firstTransactions);
    final second = _ReportPeriodTotals.from(secondTransactions);
    final activityDifference = second.activity - first.activity;
    final balanceDifference = second.balance - first.balance;
    final generatedAt = DateFormat(
      'dd MMM yyyy, h:mm a',
    ).format(DateTime.now());
    final pdf = pw.Document(
      title: 'Filer Flow Comparison Report',
      author: 'Filer Flow',
      subject: '$firstLabel compared with $secondLabel',
    );

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: pageFormat,
          margin: const pw.EdgeInsets.all(32),
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Filer Flow',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
          ],
        ),
        build: (context) => [
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#0F6B57'),
              borderRadius: pw.BorderRadius.circular(12),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Filer Flow',
                  style: pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Comparison Report',
                  style: const pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 16,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Text(
                  '$firstLabel compared with $secondLabel',
                  style: const pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 11,
                  ),
                ),
                pw.Text(
                  'Generated: $generatedAt',
                  style: const pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 9,
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(child: _comparisonPeriodCard(firstLabel, first)),
              pw.SizedBox(width: 12),
              pw.Expanded(child: _comparisonPeriodCard(secondLabel, second)),
            ],
          ),
          pw.SizedBox(height: 18),
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#E7F0EA'),
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.stretch,
              children: [
                pw.Text(
                  'Difference ($secondLabel - $firstLabel)',
                  style: pw.TextStyle(
                    fontSize: 15,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#123D36'),
                  ),
                ),
                pw.SizedBox(height: 10),
                _totalRow(
                  'Activity difference',
                  _formatSignedMoney(activityDifference),
                  emphasize: true,
                ),
                _totalRow(
                  'Balance difference',
                  _formatSignedMoney(balanceDifference),
                ),
              ],
            ),
          ),
        ],
      ),
    );
    return pdf.save();
  }

  Future<void> printReport({
    required List<Transaction> transactions,
    required String filterLabel,
  }) async {
    await Printing.layoutPdf(
      name: 'Filer Flow Transaction Report',
      onLayout: (format) => buildReport(
        transactions: transactions,
        filterLabel: filterLabel,
        pageFormat: format,
      ),
    );
  }

  Future<Uint8List> buildReport({
    required List<Transaction> transactions,
    required String filterLabel,
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    final pdf = pw.Document(
      title: 'Filer Flow Transaction Report',
      author: 'Filer Flow',
      subject: filterLabel,
    );
    final receiptImages = <int, pw.MemoryImage>{};
    for (var index = 0; index < transactions.length; index++) {
      final imagePath = transactions[index].receiptImagePath;
      if (imagePath == null || imagePath.isEmpty) continue;
      try {
        final file = File(imagePath);
        if (await file.exists()) {
          receiptImages[index] = pw.MemoryImage(await file.readAsBytes());
        }
      } on FileSystemException {
        // A missing or unreadable attachment should not block the report.
      }
    }

    final income = transactions
        .where((transaction) => !transaction.isExpense)
        .fold<double>(0, (sum, transaction) => sum + transaction.amount);
    final expenses = transactions
        .where((transaction) => transaction.isExpense)
        .fold<double>(0, (sum, transaction) => sum + transaction.amount);
    final generatedAt = DateFormat(
      'dd MMM yyyy, h:mm a',
    ).format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: pageFormat,
          margin: const pw.EdgeInsets.all(32),
          buildBackground: (context) => pw.Center(
            child: pw.Transform.rotate(
              angle: -0.30,
              child: pw.Text(
                'Filer Flow',
                style: pw.TextStyle(
                  fontSize: 76,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#F1F7F5'),
                ),
              ),
            ),
          ),
        ),
        footer: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(top: 8),
          decoration: const pw.BoxDecoration(
            border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Filer Flow',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
        ),
        build: (context) => [
          _buildHeader(filterLabel, generatedAt),
          pw.SizedBox(height: 18),
          _buildSummary(income: income, expenses: expenses),
          pw.SizedBox(height: 20),
          pw.Text(
            'Transaction details',
            style: pw.TextStyle(
              fontSize: 17,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#123D36'),
            ),
          ),
          pw.SizedBox(height: 10),
          if (transactions.isEmpty)
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(20),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#F6F7F4'),
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Text(
                'No transactions match this filter.',
                textAlign: pw.TextAlign.center,
              ),
            )
          else
            for (var index = 0; index < transactions.length; index++) ...[
              _buildTransaction(
                transactions[index],
                receiptImage: receiptImages[index],
              ),
              pw.SizedBox(height: 10),
            ],
          pw.SizedBox(height: 12),
          _buildReportTotals(income: income, expenses: expenses),
        ],
      ),
    );
    return pdf.save();
  }

  pw.Widget _buildHeader(String filterLabel, String generatedAt) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#0F6B57'),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Filer Flow',
            style: pw.TextStyle(
              color: PdfColors.white,
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Transaction Report',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 16),
          ),
          pw.SizedBox(height: 10),
          pw.Text(
            'Filter: $filterLabel',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 11),
          ),
          pw.Text(
            'Generated: $generatedAt',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 9),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSummary({required double income, required double expenses}) {
    return pw.Row(
      children: [
        pw.Expanded(child: _summaryCell('Income', _formatMoney(income))),
        pw.SizedBox(width: 8),
        pw.Expanded(child: _summaryCell('Expenses', _formatMoney(expenses))),
        pw.SizedBox(width: 8),
        pw.Expanded(
          child: _summaryCell('Balance', _formatMoney(income - expenses)),
        ),
      ],
    );
  }

  pw.Widget _summaryCell(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#E7F0EA'),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            label,
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildReportTotals({
    required double income,
    required double expenses,
  }) {
    final balance = income - expenses;
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#F6F7F4'),
        border: pw.Border.all(color: PdfColor.fromHex('#B7C9C3')),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          pw.Text(
            'Report totals',
            style: pw.TextStyle(
              fontSize: 15,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#123D36'),
            ),
          ),
          pw.SizedBox(height: 10),
          _totalRow('Total income', _formatMoney(income)),
          _totalRow('Total expenses', _formatMoney(expenses)),
          pw.Divider(color: PdfColor.fromHex('#B7C9C3')),
          _totalRow('Balance', _formatMoney(balance), emphasize: true),
        ],
      ),
    );
  }

  pw.Widget _totalRow(String label, String value, {bool emphasize = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: emphasize ? 12 : 10,
              fontWeight: emphasize ? pw.FontWeight.bold : pw.FontWeight.normal,
            ),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: emphasize ? 12 : 10,
              fontWeight: pw.FontWeight.bold,
              color: emphasize ? PdfColor.fromHex('#0F6B57') : null,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildTransaction(
    Transaction transaction, {
    pw.MemoryImage? receiptImage,
  }) {
    final amountColor = transaction.isExpense
        ? PdfColor.fromHex('#B3261E')
        : PdfColor.fromHex('#0F6B57');
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Expanded(
                      child: pw.Text(
                        transaction.title,
                        style: pw.TextStyle(
                          fontSize: 14,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColor.fromHex('#123D36'),
                        ),
                      ),
                    ),
                    pw.SizedBox(width: 10),
                    pw.Text(
                      '${transaction.isExpense ? '-' : '+'} ${_formatMoney(transaction.amount)}',
                      style: pw.TextStyle(
                        fontSize: 12,
                        fontWeight: pw.FontWeight.bold,
                        color: amountColor,
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 8),
                _detailRow(
                  'Date',
                  DateFormat('dd MMM yyyy').format(transaction.date),
                ),
                _detailRow(
                  'Type',
                  transaction.isExpense ? 'Expense' : 'Income',
                ),
                if (transaction.purpose.trim().isNotEmpty) ...[
                  pw.SizedBox(height: 3),
                  pw.Text(
                    transaction.purpose.trim(),
                    style: const pw.TextStyle(
                      fontSize: 9,
                      color: PdfColors.grey700,
                      lineSpacing: 2,
                    ),
                  ),
                ],
              ],
            ),
          ),
          if (receiptImage != null) ...[
            pw.SizedBox(width: 14),
            pw.Column(
              children: [
                pw.Container(
                  width: 105,
                  height: 105,
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: pw.BorderRadius.circular(6),
                  ),
                  child: pw.ClipRRect(
                    horizontalRadius: 6,
                    verticalRadius: 6,
                    child: pw.Image(receiptImage, fit: pw.BoxFit.cover),
                  ),
                ),
                pw.SizedBox(height: 3),
                pw.Text(
                  'Receipt image',
                  style: const pw.TextStyle(
                    fontSize: 8,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }

  pw.Widget _detailRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 3),
      child: pw.RichText(
        text: pw.TextSpan(
          children: [
            pw.TextSpan(
              text: '$label: ',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
            ),
            pw.TextSpan(
              text: value.isEmpty ? 'Not provided' : value,
              style: const pw.TextStyle(fontSize: 9),
            ),
          ],
        ),
      ),
    );
  }

  String _formatMoney(double value) {
    final sign = value < 0 ? '-' : '';
    final digits = value.abs().toStringAsFixed(2);
    final parts = digits.split('.');
    final integer = parts.first.replaceAllMapped(
      RegExp(r'\B(?=(\d{3})+(?!\d))'),
      (_) => ',',
    );
    return 'PKR $sign$integer.${parts.last}';
  }

  String _formatSignedMoney(double value) {
    final prefix = value > 0 ? '+' : '';
    return '$prefix${_formatMoney(value)}';
  }

  pw.Widget _comparisonPeriodCard(String label, _ReportPeriodTotals totals) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#123D36'),
            ),
          ),
          pw.SizedBox(height: 10),
          _totalRow('Transactions', totals.count.toString()),
          _totalRow('Income', _formatMoney(totals.income)),
          _totalRow('Expenses', _formatMoney(totals.expenses)),
          _totalRow('Activity total', _formatMoney(totals.activity)),
          pw.Divider(color: PdfColors.grey300),
          _totalRow('Balance', _formatMoney(totals.balance), emphasize: true),
        ],
      ),
    );
  }
}

class _ReportPeriodTotals {
  const _ReportPeriodTotals({
    required this.count,
    required this.income,
    required this.expenses,
  });

  factory _ReportPeriodTotals.from(List<Transaction> transactions) {
    return _ReportPeriodTotals(
      count: transactions.length,
      income: transactions
          .where((transaction) => !transaction.isExpense)
          .fold<double>(0, (sum, transaction) => sum + transaction.amount),
      expenses: transactions
          .where((transaction) => transaction.isExpense)
          .fold<double>(0, (sum, transaction) => sum + transaction.amount),
    );
  }

  final int count;
  final double income;
  final double expenses;

  double get activity => income + expenses;
  double get balance => income - expenses;
}
