import 'dart:io';
import 'dart:typed_data';

import 'package:fbr_tax_helper/features/transactions/domain/entities/transaction.dart';
import 'package:fbr_tax_helper/features/assets/domain/entities/asset.dart';
import 'package:fbr_tax_helper/features/khata/domain/entities/khata_entry.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class TransactionReportService {
  const TransactionReportService();

  Future<void> printComparisonReport({
    required List<Transaction> firstTransactions,
    required List<Transaction> secondTransactions,
    required String firstLabel,
    required String secondLabel,
  }) async {
    await Printing.layoutPdf(
      name: 'Filer Flow Comparison Report',
      onLayout: (format) => buildComparisonReport(
        firstTransactions: firstTransactions,
        secondTransactions: secondTransactions,
        firstLabel: firstLabel,
        secondLabel: secondLabel,
        pageFormat: format,
      ),
    );
  }

  Future<Uint8List> buildComparisonReport({
    required List<Transaction> firstTransactions,
    required List<Transaction> secondTransactions,
    required String firstLabel,
    required String secondLabel,
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    final first = _ReportPeriodTotals.from(firstTransactions);
    final second = _ReportPeriodTotals.from(secondTransactions);
    final incomeDifference = second.income - first.income;
    final expenseDifference = second.expenses - first.expenses;
    final balanceDifference = second.balance - first.balance;
    final generatedAt = DateFormat(
      'dd MMM yyyy, h:mm a',
    ).format(DateTime.now());
    final pdf = pw.Document(
      title: 'Filer Flow Comparison Report',
      author: 'Filer Flow',
      subject: '$firstLabel compared with $secondLabel',
    );

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: pageFormat,
          margin: const pw.EdgeInsets.all(32),
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Filer Flow',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
          ],
        ),
        build: (context) => [
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#0F6B57'),
              borderRadius: pw.BorderRadius.circular(12),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Filer Flow',
                  style: pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Comparison Report',
                  style: const pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 16,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Text(
                  '$firstLabel compared with $secondLabel',
                  style: const pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 11,
                  ),
                ),
                pw.Text(
                  'Generated: $generatedAt',
                  style: const pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 9,
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(child: _comparisonPeriodCard(firstLabel, first)),
              pw.SizedBox(width: 12),
              pw.Expanded(child: _comparisonPeriodCard(secondLabel, second)),
            ],
          ),
          pw.SizedBox(height: 18),
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#E7F0EA'),
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.stretch,
              children: [
                pw.Text(
                  'Difference ($secondLabel - $firstLabel)',
                  style: pw.TextStyle(
                    fontSize: 15,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#123D36'),
                  ),
                ),
                pw.SizedBox(height: 10),
                _totalRow(
                  'Income difference',
                  _formatSignedMoney(incomeDifference),
                ),
                _totalRow(
                  'Expense difference',
                  _formatSignedMoney(expenseDifference),
                ),
                pw.Divider(color: PdfColors.grey400),
                _totalRow(
                  'Net Balance difference',
                  _formatSignedMoney(balanceDifference),
                  emphasize: true,
                ),
              ],
            ),
          ),
        ],
      ),
    );
    return pdf.save();
  }

  Future<void> printReport({
    required List<Transaction> transactions,
    required String filterLabel,
  }) async {
    await Printing.layoutPdf(
      name: 'Filer Flow Transaction Report',
      onLayout: (format) => buildReport(
        transactions: transactions,
        filterLabel: filterLabel,
        pageFormat: format,
      ),
    );
  }

  Future<void> printFinancialReport({
    required List<Transaction> periodTransactions,
    required List<Transaction> allTransactions,
    required List<Asset> assets,
    required List<KhataEntry> khataEntries,
    required String periodLabel,
  }) async {
    await Printing.layoutPdf(
      name: 'Filer Flow Financial Report',
      onLayout: (format) => buildFinancialReport(
        periodTransactions: periodTransactions,
        allTransactions: allTransactions,
        assets: assets,
        khataEntries: khataEntries,
        periodLabel: periodLabel,
        pageFormat: format,
      ),
    );
  }

  Future<Uint8List> buildFinancialReport({
    required List<Transaction> periodTransactions,
    required List<Transaction> allTransactions,
    required List<Asset> assets,
    required List<KhataEntry> khataEntries,
    required String periodLabel,
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    final generatedAt = DateTime.now();
    final currentDate = DateFormat('dd MMM yyyy').format(generatedAt);
    final allIncome = allTransactions
        .where((transaction) => !transaction.isExpense)
        .fold<double>(0, (sum, transaction) => sum + transaction.amount);
    final allExpenses = allTransactions
        .where((transaction) => transaction.isExpense)
        .fold<double>(0, (sum, transaction) => sum + transaction.amount);
    final cash = allIncome - allExpenses;
    final assetsTotal = assets.fold<double>(
      0,
      (sum, asset) => sum + asset.value,
    );
    final receivables = khataEntries
        .where(
          (entry) => !entry.isPayable && !entry.isPaid && !entry.isWrittenOff,
        )
        .fold<double>(0, (sum, entry) => sum + entry.remainingAmount);
    final payables = khataEntries
        .where(
          (entry) => entry.isPayable && !entry.isPaid && !entry.isWrittenOff,
        )
        .fold<double>(0, (sum, entry) => sum + entry.remainingAmount);
    final netWorth = cash + assetsTotal + receivables - payables;
    final periodIncome = periodTransactions
        .where((transaction) => !transaction.isExpense)
        .fold<double>(0, (sum, transaction) => sum + transaction.amount);
    final periodExpenses = periodTransactions
        .where((transaction) => transaction.isExpense)
        .fold<double>(0, (sum, transaction) => sum + transaction.amount);
    final pdf = pw.Document(
      title: 'Filer Flow Financial Report',
      author: 'Filer Flow',
      subject: periodLabel,
    );

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: pageFormat,
          margin: const pw.EdgeInsets.all(32),
        ),
        footer: (context) => _reportFooter(context),
        build: (context) => [
          _buildFinancialHeader(periodLabel, generatedAt),
          pw.SizedBox(height: 18),
          _financialSectionTitle('Net Worth Summary (as of $currentDate)'),
          _financialSummaryGrid([
            ('Cash', _formatMoney(cash)),
            ('Total assets', _formatMoney(assetsTotal)),
            ('Receivables', _formatMoney(receivables)),
            ('Payables', _formatMoney(payables)),
            ('Total net worth', _formatMoney(netWorth)),
          ]),
          pw.SizedBox(height: 18),
          _financialSectionTitle('Assets Breakdown (as of $currentDate)'),
          _buildAssetsSection(assets),
          pw.SizedBox(height: 18),
          _financialSectionTitle('Khata Breakdown (current open balances)'),
          _buildKhataSection(khataEntries),
          pw.SizedBox(height: 18),
          _financialSectionTitle('Income & Expense Summary ($periodLabel)'),
          _buildSummary(income: periodIncome, expenses: periodExpenses),
          pw.SizedBox(height: 18),
          _financialSectionTitle('Top Categories ($periodLabel)'),
          _buildTopCategoryCards(periodTransactions),
        ],
      ),
    );
    return pdf.save();
  }

  Future<Uint8List> buildReport({
    required List<Transaction> transactions,
    required String filterLabel,
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    final pdf = pw.Document(
      title: 'Filer Flow Transaction Report',
      author: 'Filer Flow',
      subject: filterLabel,
    );
    final receiptImages = <int, pw.MemoryImage>{};
    for (var index = 0; index < transactions.length; index++) {
      final imagePath = transactions[index].receiptImagePath;
      if (imagePath == null || imagePath.isEmpty) continue;
      try {
        final file = File(imagePath);
        if (await file.exists()) {
          receiptImages[index] = pw.MemoryImage(await file.readAsBytes());
        }
      } on FileSystemException {
        // A missing or unreadable attachment should not block the report.
      }
    }

    final income = transactions
        .where((transaction) => !transaction.isExpense)
        .fold<double>(0, (sum, transaction) => sum + transaction.amount);
    final expenses = transactions
        .where((transaction) => transaction.isExpense)
        .fold<double>(0, (sum, transaction) => sum + transaction.amount);
    final generatedAt = DateFormat(
      'dd MMM yyyy, h:mm a',
    ).format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: pageFormat,
          margin: const pw.EdgeInsets.all(32),
        ),
        footer: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(top: 8),
          decoration: const pw.BoxDecoration(
            border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Filer Flow',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
        ),
        build: (context) => [
          _buildHeader(filterLabel, generatedAt),
          pw.SizedBox(height: 18),
          _buildSummary(income: income, expenses: expenses),
          pw.SizedBox(height: 20),
          pw.Text(
            'Transaction details',
            style: pw.TextStyle(
              fontSize: 17,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#123D36'),
            ),
          ),
          pw.SizedBox(height: 10),
          if (transactions.isEmpty)
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(20),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#F6F7F4'),
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Text(
                'No transactions match this filter.',
                textAlign: pw.TextAlign.center,
              ),
            )
          else
            for (var index = 0; index < transactions.length; index++) ...[
              _buildTransaction(
                transactions[index],
                receiptImage: receiptImages[index],
              ),
              pw.SizedBox(height: 10),
            ],
          pw.SizedBox(height: 12),
          _buildReportTotals(income: income, expenses: expenses),
        ],
      ),
    );
    return pdf.save();
  }

  pw.Widget _reportFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by Filer Flow',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildFinancialHeader(String periodLabel, DateTime generatedAt) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#0F6B57'),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Financial Report',
            style: pw.TextStyle(
              color: PdfColors.white,
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            'Period: $periodLabel',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 11),
          ),
          pw.Text(
            'Generated: ${DateFormat('dd MMM yyyy, h:mm a').format(generatedAt)}',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 9),
          ),
        ],
      ),
    );
  }

  pw.Widget _financialSectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(
        fontSize: 17,
        fontWeight: pw.FontWeight.bold,
        color: PdfColor.fromHex('#123D36'),
      ),
    );
  }

  pw.Widget _financialSummaryGrid(List<(String, String)> values) {
    return pw.Wrap(
      spacing: 8,
      runSpacing: 8,
      children: values
          .map(
            (value) => pw.Container(
              width: 160,
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex(
                  value.$1 == 'Total net worth' ? '#E7F0EA' : '#F6F7F4',
                ),
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(value.$1, style: const pw.TextStyle(fontSize: 9)),
                  pw.SizedBox(height: 3),
                  pw.Text(
                    value.$2,
                    style: pw.TextStyle(
                      fontSize: 11,
                      fontWeight: pw.FontWeight.bold,
                      color: value.$1 == 'Total net worth'
                          ? PdfColor.fromHex('#0F6B57')
                          : null,
                    ),
                  ),
                ],
              ),
            ),
          )
          .toList(),
    );
  }

  pw.Widget _buildAssetsSection(List<Asset> assets) {
    if (assets.isEmpty) return _emptyReportSection('None');
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300),
      columnWidths: const {
        0: pw.FlexColumnWidth(2),
        1: pw.FlexColumnWidth(1),
        2: pw.FlexColumnWidth(1),
      },
      children: [
        _tableHeader(['Asset', 'Category', 'Current value']),
        ...assets.map(
          (asset) => _tableRow([
            asset.name,
            asset.category.displayName,
            _formatMoney(asset.value),
          ]),
        ),
      ],
    );
  }

  pw.Widget _buildTopCategoryCards(List<Transaction> transactions) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Expanded(
          child: _buildTopCategoryCard(
            title: 'Top 5 Income',
            color: '#0F6B57',
            totals: _topCategoryTotals(transactions, isExpense: false),
          ),
        ),
        pw.SizedBox(width: 10),
        pw.Expanded(
          child: _buildTopCategoryCard(
            title: 'Top 5 Expenses',
            color: '#B3261E',
            totals: _topCategoryTotals(transactions, isExpense: true),
          ),
        ),
      ],
    );
  }

  List<MapEntry<String, double>> _topCategoryTotals(
    List<Transaction> transactions, {
    required bool isExpense,
  }) {
    final totals = <String, double>{};
    for (final transaction in transactions) {
      if (transaction.isExpense != isExpense) continue;
      totals.update(
        transaction.category,
        (value) => value + transaction.amount,
        ifAbsent: () => transaction.amount,
      );
    }
    return totals.entries.toList()
      ..sort((first, second) => second.value.compareTo(first.value));
  }

  pw.Widget _buildTopCategoryCard({
    required String title,
    required String color,
    required List<MapEntry<String, double>> totals,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#F6F7F4'),
        border: pw.Border.all(color: PdfColor.fromHex('#B7C9C3')),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex(color),
            ),
          ),
          pw.SizedBox(height: 6),
          if (totals.isEmpty)
            pw.Text('None', style: const pw.TextStyle(fontSize: 9))
          else
            for (final category in totals.take(5))
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 3),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Expanded(
                      child: pw.Text(
                        category.key,
                        style: const pw.TextStyle(fontSize: 9),
                      ),
                    ),
                    pw.Text(
                      _formatMoney(category.value),
                      style: pw.TextStyle(
                        fontSize: 9,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColor.fromHex(color),
                      ),
                    ),
                  ],
                ),
              ),
        ],
      ),
    );
  }

  pw.Widget _buildKhataSection(List<KhataEntry> entries) {
    final payables = entries
        .where(
          (entry) => entry.isPayable && !entry.isPaid && !entry.isWrittenOff,
        )
        .toList();
    final receivables = entries
        .where(
          (entry) => !entry.isPayable && !entry.isPaid && !entry.isWrittenOff,
        )
        .toList();
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.Text(
          'Open Payables',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
        ),
        _buildKhataTable(payables),
        pw.SizedBox(height: 10),
        pw.Text(
          'Open Receivables',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
        ),
        _buildKhataTable(receivables),
      ],
    );
  }

  pw.Widget _buildKhataTable(List<KhataEntry> entries) {
    if (entries.isEmpty) return _emptyReportSection('None');
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300),
      children: [
        _tableHeader(['Counterparty', 'Amount', 'Due date', 'Status']),
        ...entries.map((entry) {
          final dueDate = entry.dueDate;
          final overdue = dueDate != null && dueDate.isBefore(DateTime.now());
          final dueText = dueDate == null
              ? 'Not set'
              : DateFormat('dd MMM yyyy').format(dueDate);
          return _tableRow([
            entry.party,
            _formatMoney(entry.remainingAmount),
            dueText,
            overdue
                ? '${DateTime.now().difference(dueDate).inDays} days overdue'
                : 'Open',
          ]);
        }),
      ],
    );
  }

  pw.TableRow _tableHeader(List<String> values) {
    return pw.TableRow(
      decoration: pw.BoxDecoration(color: PdfColor.fromHex('#B5D7CA')),
      children: values
          .map(
            (value) => pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                value,
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 9,
                ),
              ),
            ),
          )
          .toList(),
    );
  }

  pw.TableRow _tableRow(List<String> values) {
    return pw.TableRow(
      decoration: pw.BoxDecoration(color: PdfColors.white),
      children: values
          .map(
            (value) => pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(value, style: const pw.TextStyle(fontSize: 9)),
            ),
          )
          .toList(),
    );
  }

  pw.Widget _emptyReportSection(String text) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      color: PdfColor.fromHex('#F6F7F4'),
      child: pw.Text(text, textAlign: pw.TextAlign.center),
    );
  }

  pw.Widget _buildHeader(String filterLabel, String generatedAt) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#0F6B57'),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Filer Flow',
            style: pw.TextStyle(
              color: PdfColors.white,
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Transaction Report',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 16),
          ),
          pw.SizedBox(height: 10),
          pw.Text(
            'Filter: $filterLabel',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 11),
          ),
          pw.Text(
            'Generated: $generatedAt',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 9),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSummary({required double income, required double expenses}) {
    return pw.Row(
      children: [
        pw.Expanded(child: _summaryCell('Income', _formatMoney(income))),
        pw.SizedBox(width: 8),
        pw.Expanded(child: _summaryCell('Expenses', _formatMoney(expenses))),
        pw.SizedBox(width: 8),
        pw.Expanded(
          child: _summaryCell('Balance', _formatMoney(income - expenses)),
        ),
      ],
    );
  }

  pw.Widget _summaryCell(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#E7F0EA'),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            label,
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildReportTotals({
    required double income,
    required double expenses,
  }) {
    final balance = income - expenses;
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#F6F7F4'),
        border: pw.Border.all(color: PdfColor.fromHex('#B7C9C3')),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          pw.Text(
            'Report totals',
            style: pw.TextStyle(
              fontSize: 15,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#123D36'),
            ),
          ),
          pw.SizedBox(height: 10),
          _totalRow('Total income', _formatMoney(income)),
          _totalRow('Total expenses', _formatMoney(expenses)),
          pw.Divider(color: PdfColor.fromHex('#B7C9C3')),
          _totalRow('Balance', _formatMoney(balance), emphasize: true),
        ],
      ),
    );
  }

  pw.Widget _totalRow(String label, String value, {bool emphasize = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: emphasize ? 12 : 10,
              fontWeight: emphasize ? pw.FontWeight.bold : pw.FontWeight.normal,
            ),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: emphasize ? 12 : 10,
              fontWeight: pw.FontWeight.bold,
              color: emphasize ? PdfColor.fromHex('#0F6B57') : null,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildTransaction(
    Transaction transaction, {
    pw.MemoryImage? receiptImage,
  }) {
    final amountColor = transaction.isExpense
        ? PdfColor.fromHex('#B3261E')
        : PdfColor.fromHex('#0F6B57');
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Expanded(
                      child: pw.Text(
                        transaction.title,
                        style: pw.TextStyle(
                          fontSize: 14,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColor.fromHex('#123D36'),
                        ),
                      ),
                    ),
                    pw.SizedBox(width: 10),
                    pw.Text(
                      '${transaction.isExpense ? '-' : '+'} ${_formatMoney(transaction.amount)}',
                      style: pw.TextStyle(
                        fontSize: 12,
                        fontWeight: pw.FontWeight.bold,
                        color: amountColor,
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 8),
                _detailRow(
                  'Date',
                  DateFormat('dd MMM yyyy').format(transaction.date),
                ),
                _detailRow(
                  'Type',
                  transaction.isExpense ? 'Expense' : 'Income',
                ),
                if (transaction.purpose.trim().isNotEmpty) ...[
                  pw.SizedBox(height: 3),
                  pw.Text(
                    transaction.purpose.trim(),
                    style: const pw.TextStyle(
                      fontSize: 9,
                      color: PdfColors.grey700,
                      lineSpacing: 2,
                    ),
                  ),
                ],
              ],
            ),
          ),
          if (receiptImage != null) ...[
            pw.SizedBox(width: 14),
            pw.Column(
              children: [
                pw.Container(
                  width: 105,
                  height: 105,
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: pw.BorderRadius.circular(6),
                  ),
                  child: pw.ClipRRect(
                    horizontalRadius: 6,
                    verticalRadius: 6,
                    child: pw.Image(receiptImage, fit: pw.BoxFit.cover),
                  ),
                ),
                pw.SizedBox(height: 3),
                pw.Text(
                  'Receipt image',
                  style: const pw.TextStyle(
                    fontSize: 8,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }

  pw.Widget _detailRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 3),
      child: pw.RichText(
        text: pw.TextSpan(
          children: [
            pw.TextSpan(
              text: '$label: ',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
            ),
            pw.TextSpan(
              text: value.isEmpty ? 'Not provided' : value,
              style: const pw.TextStyle(fontSize: 9),
            ),
          ],
        ),
      ),
    );
  }

  String _formatMoney(double value) {
    final sign = value < 0 ? '-' : '';
    final digits = value.abs().toStringAsFixed(2);
    final parts = digits.split('.');
    final integer = parts.first.replaceAllMapped(
      RegExp(r'\B(?=(\d{3})+(?!\d))'),
      (_) => ',',
    );
    return 'PKR $sign$integer.${parts.last}';
  }

  String _formatSignedMoney(double value) {
    final prefix = value > 0 ? '+' : '';
    return '$prefix${_formatMoney(value)}';
  }

  pw.Widget _comparisonPeriodCard(String label, _ReportPeriodTotals totals) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#123D36'),
            ),
          ),
          pw.SizedBox(height: 10),
          _totalRow('Transactions', totals.count.toString()),
          _totalRow('Income', _formatMoney(totals.income)),
          _totalRow('Expenses', _formatMoney(totals.expenses)),
          _totalRow('Activity total', _formatMoney(totals.activity)),
          pw.Divider(color: PdfColors.grey300),
          _totalRow('Balance', _formatMoney(totals.balance), emphasize: true),
        ],
      ),
    );
  }
}

class _ReportPeriodTotals {
  const _ReportPeriodTotals({
    required this.count,
    required this.income,
    required this.expenses,
  });

  factory _ReportPeriodTotals.from(List<Transaction> transactions) {
    return _ReportPeriodTotals(
      count: transactions.length,
      income: transactions
          .where((transaction) => !transaction.isExpense)
          .fold<double>(0, (sum, transaction) => sum + transaction.amount),
      expenses: transactions
          .where((transaction) => transaction.isExpense)
          .fold<double>(0, (sum, transaction) => sum + transaction.amount),
    );
  }

  final int count;
  final double income;
  final double expenses;

  double get activity => income + expenses;
  double get balance => income - expenses;
}
