import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:fbr_tax_helper/features/transactions/presentation/bloc/transaction_bloc.dart';
import 'package:fbr_tax_helper/features/transactions/presentation/pages/transaction_widgets.dart';
import 'package:fbr_tax_helper/features/auth/services/auth_service.dart';
import 'package:fbr_tax_helper/features/transactions/domain/entities/transaction.dart' as entity;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class HistoryPage extends StatelessWidget {
  final String title;
  final TransactionListMode mode;

  const HistoryPage({
    super.key,
    required this.title,
    required this.mode,
  });

  Future<void> _printHistory(BuildContext context, List<entity.Transaction> transactions) async {
    final pdf = pw.Document();
    
    // Filter transactions to match what is displayed
    final displayTransactions = transactions.where((t) {
      if (mode == TransactionListMode.khata) return t.khataEntryId != null;
      if (mode == TransactionListMode.asset) return t.assetId != null;
      return t.khataEntryId == null && t.assetId == null;
    }).toList();

    final generatedAt = DateFormat('dd MMM yyyy, h:mm a').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Filer Flow',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
          ],
        ),
        build: (pw.Context context) {
          return [
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(20),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#0F6B57'),
                borderRadius: pw.BorderRadius.circular(12),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Filer Flow',
                    style: pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'History Report',
                    style: const pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 16,
                    ),
                  ),
                  pw.SizedBox(height: 10),
                  pw.Text(
                    title,
                    style: const pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 11,
                    ),
                  ),
                  pw.Text(
                    'Generated: $generatedAt',
                    style: const pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 9,
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.TableHelper.fromTextArray(
              context: context,
              headers: ['Date', 'Category', 'Description', 'Amount', 'Type'],
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
              headerDecoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#0F6B57'),
              ),
              rowDecoration: const pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(
                    color: PdfColors.grey300,
                    width: 0.5,
                  ),
                ),
              ),
              cellAlignment: pw.Alignment.centerLeft,
              data: displayTransactions.map((t) {
                return [
                  DateFormat('MMM d, yyyy').format(t.date),
                  t.category,
                  t.title,
                  'PKR ${t.amount.toStringAsFixed(2)}',
                  t.isExpense ? 'Expense/Debit' : 'Income/Credit'
                ];
              }).toList(),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
        actions: [
          BlocBuilder<TransactionBloc, TransactionState>(
            builder: (context, state) {
              if (state is TransactionLoaded) {
                return IconButton(
                  icon: const Icon(Icons.print),
                  onPressed: () => _printHistory(context, state.transactions),
                  tooltip: 'Print History',
                );
              }
              return const SizedBox.shrink();
            },
          ),
        ],
      ),
      body: BlocBuilder<TransactionBloc, TransactionState>(
        builder: (context, state) {
          if (state is TransactionLoading) {
            return const Center(child: CircularProgressIndicator());
          } else if (state is TransactionLoaded) {
            final userId = context.read<AuthService>().currentUser?.uid ?? '';
            return SingleChildScrollView(
              padding: const EdgeInsets.symmetric(vertical: 16),
              child: TransactionList(
                state: state,
                currentUserId: userId,
                transactions: state.transactions,
                mode: mode,
              ),
            );
          } else if (state is TransactionError) {
            return Center(child: Text(state.message));
          }
          return const SizedBox.shrink();
        },
      ),
    );
  }
}
