// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoZAP0bSsOnxs2C4fQ0ww6pKPp7c9eymo',
    appId: '1:422412426431:web:56e7b1b5ffe61bc094fa0a',
    messagingSenderId: '422412426431',
    projectId: 'taxflutter-application',
    authDomain: 'taxflutter-application.firebaseapp.com',
    storageBucket: 'taxflutter-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFzfxLM2TAjlnLCxiPL8HBQYGSXuQIRtA',
    appId: '1:422412426431:android:0ec59dee7303c47c94fa0a',
    messagingSenderId: '422412426431',
    projectId: 'taxflutter-application',
    storageBucket: 'taxflutter-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_eow5pSD7JwBXzi7_4bhfyyEo1JNF_Bw',
    appId: '1:422412426431:ios:9f1e8fcbecc5494a94fa0a',
    messagingSenderId: '422412426431',
    projectId: 'taxflutter-application',
    storageBucket: 'taxflutter-application.firebasestorage.app',
    androidClientId:
        '422412426431-9jvn8auo7tua7toiu3u33kouga8ckehk.apps.googleusercontent.com',
    iosClientId:
        '422412426431-i4ijurbhl7srbsb704bkkkjk0dipruju.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbrTaxHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_eow5pSD7JwBXzi7_4bhfyyEo1JNF_Bw',
    appId: '1:422412426431:ios:9f1e8fcbecc5494a94fa0a',
    messagingSenderId: '422412426431',
    projectId: 'taxflutter-application',
    storageBucket: 'taxflutter-application.firebasestorage.app',
    androidClientId:
        '422412426431-9jvn8auo7tua7toiu3u33kouga8ckehk.apps.googleusercontent.com',
    iosClientId:
        '422412426431-i4ijurbhl7srbsb704bkkkjk0dipruju.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbrTaxHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoZAP0bSsOnxs2C4fQ0ww6pKPp7c9eymo',
    appId: '1:422412426431:web:d3ad07b581fde37d94fa0a',
    messagingSenderId: '422412426431',
    projectId: 'taxflutter-application',
    authDomain: 'taxflutter-application.firebaseapp.com',
    storageBucket: 'taxflutter-application.firebasestorage.app',
  );
}
